name: Docker Builds, Validation and Pushes to AWS ECR

on:
  push:
    branches:
      - main
    paths:
      - 'docker/cbdb/build/rocky9/**'

  workflow_dispatch: # Manual trigger

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      rocky9_changed:    ${{ steps.platform-filter.outputs.rocky9 }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: platform-filter
        with:
          filters: |
            rocky9:
              - 'docker/cbdb/build/rocky9/**'

  cbdb-build-rocky9:
    needs: changes
    if: ${{ needs.changes.outputs.rocky9_changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker image for cbdb-build-rocky9
        uses: docker/build-push-action@v6
        with:
          context: ./docker/cbdb/build/rocky9
          push: false  # Do not push to registry yet
          load: true   # Load the image into the local Docker daemon
          tags: |
            cbdb-build-rocky9:latest

      - name: List Docker images
        run: docker images

      - name: Run Testinfra Tests
        id: test
        run: |
          # Run the container with the hostname and keep it alive using a sleep command
          docker run -d -h cdw --name cbdb-build-rocky9-test cbdb-build-rocky9:latest bash -c "sleep 30"
          # Execute the tests within the running container
          docker exec cbdb-build-rocky9-test pytest --cache-clear --disable-warnings -p no:warnings /tests/testinfra/test_cloudberry_db_env.py

      - name: Remove Test Container
        if: always()
        run: docker rm -f cbdb-build-rocky9-test

      - name: Retag and Push Docker image to ECR
        if: steps.test.outcome == 'success'
        uses: docker/build-push-action@v6
        with:
          context: ./docker/cbdb/build/rocky9
          push: true
          tags: |
            ${{ secrets.ECR_PUBLIC_ENDPOINT }}/cbdb/build/rocky9:latest
