name: Docker CBDB Release Builds and Pushes to AWS ECR

on:
  push:
    branches:
      - main
    paths:
      - 'docker/cbdb/release/rocky8/**'
      - 'docker/cbdb/release/rocky9/**'

  workflow_dispatch: # Manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['rocky8', 'rocky9']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine if platform changed
        id: platform-filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            rocky8:
              - 'docker/cbdb/relase/rocky8/**'
            rocky9:
              - 'docker/cbdb/relase/rocky9/**'

      - name: Skip if not relevant
        if: ${{ steps.platform-filter.outputs[matrix.platform] != 'true' }}
        run: echo "Skipping because the changes do not affect this platform"

      - name: Login to Docker Hub
        if: ${{ steps.platform-filter.outputs[matrix.platform] == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS credentials
        if: ${{ steps.platform-filter.outputs[matrix.platform] == 'true' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        if: ${{ steps.platform-filter.outputs[matrix.platform] == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR Public
        if: ${{ steps.platform-filter.outputs[matrix.platform] == 'true' }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker image for cbdb-relase-${{ matrix.platform }}
        if: ${{ steps.platform-filter.outputs[matrix.platform] == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: ./docker/cbdb/relase/${{ matrix.platform }}
          push: true
          tags: |
            cbdb-relase-${{ matrix.platform }}:latest
